# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import file_state_pb2 as file__state__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in file_state_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileStateStub(object):
    """The FileState service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExistsInState = channel.unary_unary(
                '/FileState/ExistsInState',
                request_serializer=file__state__pb2.ExistsInStateRequest.SerializeToString,
                response_deserializer=file__state__pb2.ExistsInStateResponse.FromString,
                _registered_method=True)


class FileStateServicer(object):
    """The FileState service definition.
    """

    def ExistsInState(self, request, context):
        """RPC service with request/response information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileStateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExistsInState': grpc.unary_unary_rpc_method_handler(
                    servicer.ExistsInState,
                    request_deserializer=file__state__pb2.ExistsInStateRequest.FromString,
                    response_serializer=file__state__pb2.ExistsInStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileState', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FileState', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileState(object):
    """The FileState service definition.
    """

    @staticmethod
    def ExistsInState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileState/ExistsInState',
            file__state__pb2.ExistsInStateRequest.SerializeToString,
            file__state__pb2.ExistsInStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
