# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66ile_state.proto\"$\n\x14\x45xistsInStateRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\'\n\x15\x45xistsInStateResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32M\n\tFileState\x12@\n\rExistsInState\x12\x15.ExistsInStateRequest\x1a\x16.ExistsInStateResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_state_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXISTSINSTATEREQUEST._serialized_start=20
  _EXISTSINSTATEREQUEST._serialized_end=56
  _EXISTSINSTATERESPONSE._serialized_start=58
  _EXISTSINSTATERESPONSE._serialized_end=97
  _FILESTATE._serialized_start=99
  _FILESTATE._serialized_end=176
# @@protoc_insertion_point(module_scope)
